import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/style.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import Chat from "@/components/Chat";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NewsEra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  const systemPref = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  const appliedTheme = theme || systemPref;
                  document.documentElement.classList.add(appliedTheme);
                } catch(e) {}
              })();
            `,
          }}
        />
        <meta name="theme-color" content="#000000" />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <ReduxProvider>
            <ReactQueryProvider>
              {children} <Chat />
            </ReactQueryProvider>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
