import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import AuthWrapper from "@/providers/AuthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NewsEra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className={inter.className}>
        <ReduxProvider>
          <AuthWrapper>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </AuthWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
